name: CI Pipeline

on:
  pull_request:
    branches: [ "development", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Check formatting (Spotless)
        run: ./gradlew spotlessCheck

      - name: Build project
        run: ./gradlew build